# Generated by Django 4.1.7 on 2023-11-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("disease", "0005_alter_book_table_buy_link_alter_case_table_age_and_more"),
        ("analytics", "0002_remove_historicaltest_table_history_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="data_analytics_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.IntegerField(default=0)),
                (
                    "data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.data_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="case_analytics_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.IntegerField(default=0)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.case_table",
                    ),
                ),
            ],
        ),
    ]
