# Generated by Django 4.1.7 on 2023-11-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("disease", "0005_alter_book_table_buy_link_alter_case_table_age_and_more"),
        ("analytics", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="disease_analytics_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.IntegerField(default=0)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.disease_table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="pathy_analytics_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.IntegerField(default=0)),
                (
                    "pathy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.pathy_table",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="data_analytics_table",
            name="data",
        ),
        migrations.DeleteModel(
            name="case_analytics_table",
        ),
        migrations.DeleteModel(
            name="data_analytics_table",
        ),
    ]
