# Generated by Django 4.1.7 on 2023-09-19 20:37

import clinics.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinics_table",
            name="image",
            field=models.ImageField(
                upload_to="clinics_images/",
                validators=[clinics.models.validate_webp_image],
            ),
        ),
        migrations.AlterField(
            model_name="historicalclinics_table",
            name="image",
            field=models.TextField(
                max_length=100, validators=[clinics.models.validate_webp_image]
            ),
        ),
    ]
