# Generated by Django 4.1.7 on 2024-01-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0002_alter_clinics_table_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinics_table",
            name="address",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="clinics_table",
            name="locationLink",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="historicalclinics_table",
            name="address",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="historicalclinics_table",
            name="locationLink",
            field=models.URLField(null=True),
        ),
    ]
