# Generated by Django 4.1.7 on 2023-08-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ejournal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ejournal_table",
            name="file",
            field=models.FileField(upload_to="ejournal/files/"),
        ),
        migrations.AlterField(
            model_name="ejournal_table",
            name="image",
            field=models.ImageField(upload_to="ejournal/cover_images/"),
        ),
    ]
