# Generated by Django 4.1.7 on 2023-04-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_key_value_table_testimonial_table_video_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video_table",
            name="image_link",
        ),
        migrations.AddField(
            model_name="video_table",
            name="image",
            field=models.ImageField(null=True, upload_to="video_table_images/"),
        ),
    ]
