# Generated by Django 4.1.7 on 2023-04-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_video_table_image_link_video_table_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video_table",
            name="image",
            field=models.ImageField(upload_to="video_table_images/"),
        ),
    ]
