# Generated by Django 4.1.7 on 2023-04-04 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_disease_table_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disease_table",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="key_value_table",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="testimonial_table",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="video_table",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="disease_table",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 4, 10, 54, 36, 294934)
            ),
        ),
        migrations.AlterField(
            model_name="key_value_table",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 4, 10, 54, 36, 295804)
            ),
        ),
        migrations.AlterField(
            model_name="testimonial_table",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 4, 10, 54, 36, 295206)
            ),
        ),
        migrations.AlterField(
            model_name="video_table",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 4, 10, 54, 36, 295472)
            ),
        ),
    ]
