# Generated by Django 4.1.7 on 2023-04-04 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_disease_table_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disease_table",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="key_value_table",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="testimonial_table",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="video_table",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="disease_table",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="key_value_table",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="testimonial_table",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="video_table",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="disease_table",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 4, 19, 59, 9, 429161, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="disease_table",
            name="modified_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 4, 19, 59, 9, 429366, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="key_value_table",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 4, 19, 59, 9, 430298, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="key_value_table",
            name="modified_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 4, 19, 59, 9, 430305, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="testimonial_table",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 4, 19, 59, 9, 429690, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="testimonial_table",
            name="modified_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 4, 19, 59, 9, 429699, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="video_table",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 4, 19, 59, 9, 429976, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="video_table",
            name="modified_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 4, 19, 59, 9, 429985, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
