# Generated by Django 4.1.7 on 2023-07-22 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_alter_disease_table_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="disease_table",
        ),
    ]
