# Generated by Django 4.1.7 on 2023-08-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_delete_disease_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="video_table",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
