# Generated by Django 4.1.7 on 2023-10-03 08:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import user_forms.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_forms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historicaljoin_us_table",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Age can not be negative"
                            ),
                            django.core.validators.MaxValueValidator(
                                200, "Age can't be greater than 200"
                            ),
                        ]
                    ),
                ),
                ("gender", models.CharField(max_length=200)),
                ("email_address", models.CharField(max_length=300)),
                ("phone_number", models.CharField(max_length=200)),
                ("pincode", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=500)),
                ("state", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("profession", models.CharField(max_length=300)),
                ("message", models.TextField()),
                (
                    "photograph",
                    models.TextField(
                        max_length=100,
                        validators=[user_forms.models.validate_jpg_jpeg_png_image],
                    ),
                ),
                (
                    "document",
                    models.TextField(
                        max_length=100, validators=[user_forms.models.validate_pdf_file]
                    ),
                ),
                ("email_verfied", models.BooleanField(default=False)),
                ("identity_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical join_us_table",
                "verbose_name_plural": "historical join_us_tables",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="join_us_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Age can not be negative"
                            ),
                            django.core.validators.MaxValueValidator(
                                200, "Age can't be greater than 200"
                            ),
                        ]
                    ),
                ),
                ("gender", models.CharField(max_length=200)),
                ("email_address", models.CharField(max_length=300)),
                ("phone_number", models.CharField(max_length=200)),
                ("pincode", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=500)),
                ("state", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("profession", models.CharField(max_length=300)),
                ("message", models.TextField()),
                (
                    "photograph",
                    models.ImageField(
                        upload_to="join_us/images/",
                        validators=[user_forms.models.validate_jpg_jpeg_png_image],
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="join_us/documents/",
                        validators=[user_forms.models.validate_pdf_file],
                    ),
                ),
                ("email_verfied", models.BooleanField(default=False)),
                ("identity_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="test_form",
        ),
    ]
