# Generated by Django 4.1.7 on 2023-10-10 17:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import user_forms.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_forms", "0003_share_experience_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ask_suggestion_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Age can not be negative"
                            ),
                            django.core.validators.MaxValueValidator(
                                200, "Age can't be greater than 200"
                            ),
                        ]
                    ),
                ),
                ("gender", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=500)),
                ("state", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("email_address", models.CharField(max_length=300)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("disease", models.CharField(blank=True, max_length=500, null=True)),
                ("pathies", models.TextField(blank=True, null=True)),
                ("query", models.TextField()),
                ("show_study", models.BooleanField(default=True)),
                ("show_email", models.BooleanField(default=False)),
                (
                    "reports",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ask_suggestion/",
                        validators=[user_forms.models.validate_pdf_file],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="historicalshare_experience_table",
            name="date_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalshare_experience_table",
            name="date_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalshare_experience_table",
            name="disease",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="historicalshare_experience_table",
            name="pathies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalshare_experience_table",
            name="phone_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicalshare_experience_table",
            name="preferred_communication",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalshare_experience_table",
            name="reports",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[user_forms.models.validate_pdf_file],
            ),
        ),
        migrations.AlterField(
            model_name="share_experience_table",
            name="date_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="share_experience_table",
            name="date_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="share_experience_table",
            name="disease",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="share_experience_table",
            name="pathies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="share_experience_table",
            name="phone_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="share_experience_table",
            name="preferred_communication",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="share_experience_table",
            name="reports",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="share_experience/",
                validators=[user_forms.models.validate_pdf_file],
            ),
        ),
        migrations.CreateModel(
            name="Historicalask_suggestion_table",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Age can not be negative"
                            ),
                            django.core.validators.MaxValueValidator(
                                200, "Age can't be greater than 200"
                            ),
                        ]
                    ),
                ),
                ("gender", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=500)),
                ("state", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("email_address", models.CharField(max_length=300)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("disease", models.CharField(blank=True, max_length=500, null=True)),
                ("pathies", models.TextField(blank=True, null=True)),
                ("query", models.TextField()),
                ("show_study", models.BooleanField(default=True)),
                ("show_email", models.BooleanField(default=False)),
                (
                    "reports",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        validators=[user_forms.models.validate_pdf_file],
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ask_suggestion_table",
                "verbose_name_plural": "historical ask_suggestion_tables",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
