# Generated by Django 4.1.7 on 2023-04-04 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="footer_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 4, 4, 11, 18, 43, 22666)
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField(max_length=1000)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
