# Generated by Django 4.1.7 on 2023-04-04 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0005_alter_footer_table_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer_table",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="footer_table",
            name="modified_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
