# Generated by Django 4.1.7 on 2023-04-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footer", "0006_alter_footer_table_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer_table",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="footer_table",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
