# Generated by Django 4.1.7 on 2023-07-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="disease_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("show", models.BooleanField(default=True)),
                ("text", models.TextField()),
                ("summary", models.TextField()),
                ("image_link", models.ImageField(upload_to="disease_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="pathy_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("show", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("therapiesWithDrugs", "therapiesWithDrugs"),
                            ("therapiesWithoutDrugs", "therapiesWithoutDrugs"),
                            ("lessKnownTherapies", "lessKnownTherapies"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image_link", models.ImageField(upload_to="pathy_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.disease_table",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="sex_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sex", models.CharField(max_length=1000)),
                ("show", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="source_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("books", "books"),
                            ("socialMedia", "socialMedia"),
                            ("youtube", "youtube"),
                            ("website", "website"),
                            ("article", "article"),
                            ("quora", "quora"),
                            ("directCase", "directCase"),
                        ],
                        max_length=1000,
                    ),
                ),
                ("text", models.TextField()),
                ("show", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="whatsapp_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=2000)),
                ("value", models.TextField()),
                ("show", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.disease_table",
                    ),
                ),
                (
                    "pathy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.pathy_table",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="summary_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.disease_table",
                    ),
                ),
                (
                    "pathy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.pathy_table",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="data_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=1000)),
                ("link", models.CharField(max_length=2000)),
                ("summary", models.TextField()),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.disease_table",
                    ),
                ),
                (
                    "pathy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.pathy_table",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.source_table",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="case_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("summary", models.TextField()),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                ("first_name", models.CharField(max_length=1000)),
                ("last_name", models.CharField(max_length=1000)),
                ("age", models.IntegerField()),
                ("occupation", models.CharField(max_length=1000)),
                ("email_address", models.CharField(max_length=1000)),
                ("phone_number", models.CharField(max_length=50)),
                ("street_address", models.CharField(max_length=1000)),
                ("zip_code", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=1000)),
                ("country", models.CharField(max_length=1000)),
                ("history_link", models.URLField(max_length=2000)),
                ("allergies_link", models.URLField(max_length=2000)),
                ("reports_link", models.URLField(max_length=2000)),
                ("show", models.BooleanField(default=True)),
                ("show_name", models.BooleanField(default=False)),
                ("show_email", models.BooleanField(default=False)),
                ("show_phone_number", models.BooleanField(default=False)),
                ("show_address", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.disease_table",
                    ),
                ),
                (
                    "pathy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.pathy_table",
                    ),
                ),
                (
                    "sex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.sex_table",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="book_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=1000)),
                ("author", models.CharField(max_length=1000)),
                ("rating", models.IntegerField()),
                ("text", models.TextField()),
                ("image_link", models.ImageField(upload_to="book_images/")),
                ("buy_link", models.URLField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.disease_table",
                    ),
                ),
                (
                    "pathy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disease.pathy_table",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
