# Generated by Django 4.1.7 on 2023-08-18 08:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("disease", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book_table",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="case_table",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="data_table",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="summary_table",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="whatsapp_table",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="whatsapp_table",
            name="key",
        ),
        migrations.RemoveField(
            model_name="whatsapp_table",
            name="value",
        ),
        migrations.AddField(
            model_name="whatsapp_table",
            name="link",
            field=models.URLField(default="healthumbrella.org"),
        ),
        migrations.AlterField(
            model_name="book_table",
            name="buy_link",
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="book_table",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "rating should be greater than or equal to 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "rating should be less than or equal to 10"
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="age",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "age should be greater than or equal to 1"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="allergies_link",
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="country",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="email_address",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="first_name",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="history_link",
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="last_name",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="occupation",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="phone_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "rating should be greater than or equal to 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "rating should be less than or equal to 10"
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="reports_link",
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="state",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="street_address",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="zip_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="data_table",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "rating should be greater than or equal to 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "rating should be less than or equal to 10"
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="data_table",
            name="source",
            field=models.ForeignKey(
                limit_choices_to={
                    "name__in": [
                        "books",
                        "socialMedia",
                        "youtube",
                        "website",
                        "article",
                        "quora",
                    ]
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="disease.source_table",
            ),
        ),
    ]
