# Generated by Django 4.1.7 on 2023-09-19 16:06

import disease.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disease", "0003_historicalwhatsapp_table_historicalsummary_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book_table",
            name="author",
            field=models.CharField(
                max_length=1000, validators=[disease.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="book_table",
            name="image_link",
            field=models.ImageField(
                upload_to="book_images/",
                validators=[disease.models.validate_webp_image],
            ),
        ),
        migrations.AlterField(
            model_name="book_table",
            name="name",
            field=models.CharField(
                max_length=1000, validators=[disease.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="email_address",
            field=models.CharField(
                max_length=1000,
                null=True,
                validators=[disease.models.validate_small_letters],
            ),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="first_name",
            field=models.CharField(
                max_length=1000,
                null=True,
                validators=[disease.models.validate_small_letters],
            ),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="last_name",
            field=models.CharField(
                max_length=1000,
                null=True,
                validators=[disease.models.validate_small_letters],
            ),
        ),
        migrations.AlterField(
            model_name="case_table",
            name="title",
            field=models.CharField(
                max_length=1000, validators=[disease.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="data_table",
            name="title",
            field=models.CharField(
                max_length=1000, validators=[disease.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="disease_table",
            name="image_link",
            field=models.ImageField(
                upload_to="disease_images/",
                validators=[disease.models.validate_webp_image],
            ),
        ),
        migrations.AlterField(
            model_name="disease_table",
            name="name",
            field=models.CharField(
                max_length=1000, validators=[disease.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="historicalbook_table",
            name="author",
            field=models.CharField(
                max_length=1000, validators=[disease.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="historicalbook_table",
            name="image_link",
            field=models.TextField(
                max_length=100, validators=[disease.models.validate_webp_image]
            ),
        ),
        migrations.AlterField(
            model_name="historicalbook_table",
            name="name",
            field=models.CharField(
                max_length=1000, validators=[disease.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase_table",
            name="email_address",
            field=models.CharField(
                max_length=1000,
                null=True,
                validators=[disease.models.validate_small_letters],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase_table",
            name="first_name",
            field=models.CharField(
                max_length=1000,
                null=True,
                validators=[disease.models.validate_small_letters],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase_table",
            name="last_name",
            field=models.CharField(
                max_length=1000,
                null=True,
                validators=[disease.models.validate_small_letters],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcase_table",
            name="title",
            field=models.CharField(
                max_length=1000, validators=[disease.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="historicaldata_table",
            name="title",
            field=models.CharField(
                max_length=1000, validators=[disease.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="historicaldisease_table",
            name="image_link",
            field=models.TextField(
                max_length=100, validators=[disease.models.validate_webp_image]
            ),
        ),
        migrations.AlterField(
            model_name="historicaldisease_table",
            name="name",
            field=models.CharField(
                max_length=1000, validators=[disease.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="historicalpathy_table",
            name="image_link",
            field=models.TextField(
                max_length=100, validators=[disease.models.validate_webp_image]
            ),
        ),
        migrations.AlterField(
            model_name="historicalsex_table",
            name="sex",
            field=models.CharField(
                max_length=1000, validators=[disease.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="historicalsource_table",
            name="name",
            field=models.CharField(
                choices=[
                    ("books", "books"),
                    ("socialMedia", "socialMedia"),
                    ("youtube", "youtube"),
                    ("website", "website"),
                    ("article", "article"),
                    ("quora", "quora"),
                    ("directCase", "directCase"),
                ],
                max_length=1000,
                validators=[disease.models.validate_small_letters],
            ),
        ),
        migrations.AlterField(
            model_name="pathy_table",
            name="image_link",
            field=models.ImageField(
                upload_to="pathy_images/",
                validators=[disease.models.validate_webp_image],
            ),
        ),
        migrations.AlterField(
            model_name="sex_table",
            name="sex",
            field=models.CharField(
                max_length=1000, validators=[disease.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="source_table",
            name="name",
            field=models.CharField(
                choices=[
                    ("books", "books"),
                    ("socialMedia", "socialMedia"),
                    ("youtube", "youtube"),
                    ("website", "website"),
                    ("article", "article"),
                    ("quora", "quora"),
                    ("directCase", "directCase"),
                ],
                max_length=1000,
                validators=[disease.models.validate_small_letters],
            ),
        ),
    ]
