# Generated by Django 4.1.7 on 2023-09-19 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="key_value_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="members_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        upload_to="members_images/",
                        validators=[members.models.validate_webp_image],
                    ),
                ),
                ("designation", models.CharField(max_length=200)),
                ("about", models.CharField(max_length=400)),
                (
                    "team",
                    models.CharField(
                        choices=[
                            ("lead-members", "lead-members"),
                            ("data-management-team", "data-management-team"),
                            ("regional-representatives", "regional-representatives"),
                            ("our-well-wishers", "our-well-wishers"),
                            ("website-management-team", "website-management-team"),
                            ("our-members", "our-members"),
                        ],
                        max_length=100,
                    ),
                ),
                ("linkedin_url", models.URLField(null=True)),
                ("email_address", models.EmailField(max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=30, null=True)),
                ("show", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Historicalmembers_table",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "image",
                    models.TextField(
                        max_length=100, validators=[members.models.validate_webp_image]
                    ),
                ),
                ("designation", models.CharField(max_length=200)),
                ("about", models.CharField(max_length=400)),
                (
                    "team",
                    models.CharField(
                        choices=[
                            ("lead-members", "lead-members"),
                            ("data-management-team", "data-management-team"),
                            ("regional-representatives", "regional-representatives"),
                            ("our-well-wishers", "our-well-wishers"),
                            ("website-management-team", "website-management-team"),
                            ("our-members", "our-members"),
                        ],
                        max_length=100,
                    ),
                ),
                ("linkedin_url", models.URLField(null=True)),
                ("email_address", models.EmailField(max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=30, null=True)),
                ("show", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical members_table",
                "verbose_name_plural": "historical members_tables",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Historicalkey_value_table",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical key_value_table",
                "verbose_name_plural": "historical key_value_tables",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
