# Generated by Django 4.1.7 on 2023-09-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_key_value_table_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmembers_table",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmembers_table",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmembers_table",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="members_table",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="members_table",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="members_table",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
