# Generated by Django 4.1.7 on 2023-08-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pathy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="effective_table",
            name="show",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="pathy_table",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
