# Generated by Django 4.1.7 on 2023-09-19 16:06

from django.db import migrations, models
import pathy.models


class Migration(migrations.Migration):
    dependencies = [
        ("pathy", "0003_historicalpathy_table_historicaleffective_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="effective_table",
            name="name",
            field=models.CharField(
                max_length=1000, validators=[pathy.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="historicaleffective_table",
            name="name",
            field=models.CharField(
                max_length=1000, validators=[pathy.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="historicalpathy_table",
            name="image",
            field=models.TextField(
                max_length=100, validators=[pathy.models.validate_webp_image]
            ),
        ),
        migrations.AlterField(
            model_name="historicalpathy_table",
            name="title",
            field=models.CharField(
                max_length=1000, validators=[pathy.models.validate_small_letters]
            ),
        ),
        migrations.AlterField(
            model_name="pathy_table",
            name="image",
            field=models.ImageField(
                upload_to="pathy_section_images/",
                validators=[pathy.models.validate_webp_image],
            ),
        ),
        migrations.AlterField(
            model_name="pathy_table",
            name="title",
            field=models.CharField(
                max_length=1000, validators=[pathy.models.validate_small_letters]
            ),
        ),
    ]
